name: movieverse
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  flutter_screenutil: ^5.9.0
  go_router: ^12.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.0
  google_sign_in: ^6.1.5
  dio: ^5.3.3
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/.env
  #   - images/a_dot_ham.jpeg




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
